### ISSUE TITLE
Android app: java.lang.NullPointerException: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by lefoumalade451** [passbolt/passbolt_docker#189]
Hello Passbolt,
I am having issue pairing my android device to my dockerized passbolt, once the QR code are scanned by the app, I type my password and I got "Devices pair successfully" then it goes to login page again, I put the password etc...

Passbolt App log:
```
Passbolt Android logs: 
Device: OnePlus AC2003
Android 12 (31)
Passbolt 1.11.0-14

16:58:58 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json h2 (41-byte body)
16:58:58 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json (73ms, unknown-length body)
16:58:58 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json h2 (41-byte body)
16:58:59 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json (164ms, unknown-length body)
16:58:59 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json h2 (41-byte body)
16:58:59 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json (61ms, unknown-length body)
16:59:00 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json h2 (41-byte body)
16:59:00 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json (56ms, unknown-length body)
16:59:00 Saving private key.
16:59:00 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json?contain%5Buser.profile%5D=1 h2 (38-byte body)
16:59:00 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json?contain%5Buser.profile%5D=1 (76ms, unknown-length body)
16:59:01 Checking biometry state
16:59:02 --> GET https://passbolt-url.com/img/avatar/user_medium.png h2
16:59:02 <-- 200 https://passbolt-url.com/img/avatar/user_medium.png (4ms, 2921-byte body)
16:59:02 Received fill request
16:59:02 Visiting view node with id: -1 scheme + domain: null://null package: null content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131361858 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131361874 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362129 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362129 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362584 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: -1 scheme + domain: null://null package: null content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362310 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362070 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362047 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362357 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362581 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362561 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362188 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 129 
16:59:02 Visiting view node with id: -1 scheme + domain: null://null package: null content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: -1 scheme + domain: null://null package: null content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362575 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131361922 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131361920 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362128 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Parsed domain: 
16:59:02 Did not find any autofillable views
16:59:10 Passphrase cache cleared
16:59:10 Passphrase cached
16:59:10 Getting server pgp and rsa keys
16:59:10 --> GET https://passbolt-url.com/auth/verify.json h2
16:59:10 <-- 200 https://passbolt-url.com/auth/verify.json (76ms, unknown-length body)
16:59:10 Uncaught exception in thread: main
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter publicKey
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$Output$Success.<init>(Unknown Source:2)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase.execute(GetServerPublicPgpKeyUseCase.kt:38)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$execute$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a6284b2, Dispatchers.Main]

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter publicKey
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$Output$Success.<init>(Unknown Source:2)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase.execute(GetServerPublicPgpKeyUseCase.kt:38)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$execute$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a6284b2, Dispatchers.Main]
16:59:10 Uncaught exception in thread: main
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter publicKey
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$Output$Success.<init>(Unknown Source:2)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase.execute(GetServerPublicPgpKeyUseCase.kt:38)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$execute$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a6284b2, Dispatchers.Main]

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter publicKey
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$Output$Success.<init>(Unknown Source:2)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase.execute(GetServerPublicPgpKeyUseCase.kt:38)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$execute$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a6284b2, Dispatchers.Main]
16:59:10 File logging tree planted
16:59:12 Checking biometry state
17:01:25 Checking biometry state
17:01:26 Checking biometry state
```

Docker logs:
```
passbolt-passbolt-1     | 2023-01-22 17:31:26,625 INFO reaped unknown pid 2046 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,625 INFO reaped unknown pid 2048 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2051 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2053 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2055 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2057 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2059 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2062 (exit status 0)
```

Many thanks!

**Comment by stripthis** [comment]
Hello, can you repost your issue on the android repository? Thank you !
https://github.com/passbolt/passbolt_docker/issues
