### ISSUE TITLE
create admin user after deployment

### ISSUE THREAD

**Issue by Sispheor** [passbolt/passbolt_docker#44]
Hi, I'm sorry but I don't find in the doc of this repo how to get connected to the interface as admin.
So, I followed the[ install doc](https://www.passbolt.com/help/tech/install) and

I tried to create a user
```
/var/www/passbolt/app/Console/cake register_user -u john.doe@domain.com -f john -l doe-r admin
```

This is the output I have
```
Error: Plugin RegisterUser could not be found.
#0 /var/www/passbolt/lib/Cake/Core/App.php(227): CakePlugin::path('RegisterUser')
#1 /var/www/passbolt/lib/Cake/Core/App.php(549): App::path('Console/Command', 'RegisterUser')
#2 [internal function]: App::load('RegisterUserShe...')
#3 [internal function]: spl_autoload_call('RegisterUserShe...')
#4 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(264): class_exists('RegisterUserShe...')
#5 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(210): ShellDispatcher->_getShell('register_user')
#6 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/passbolt/app/Console/cake.php(47): ShellDispatcher::run(Array)
#8 {main}
```

**Comment by stripthis** [comment]
It should be 
/var/www/passbolt/app/Console/cake **passbolt** register_user

**Comment by Sispheor** [comment]
You are right. PEBCAK issue. Sorry ! :)
